// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqJVG1-6rkHikpWcsq1rPs6pDY_a7cyvg',
    appId: '1:724715921216:web:e2d5e977bc831d058524a5',
    messagingSenderId: '724715921216',
    projectId: 'strm-mobdev',
    authDomain: 'strm-mobdev.firebaseapp.com',
    storageBucket: 'strm-mobdev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6PJMuTYhTISzw87P96tJTNPL1lRr0nHs',
    appId: '1:724715921216:android:f169f1d6c42059058524a5',
    messagingSenderId: '724715921216',
    projectId: 'strm-mobdev',
    storageBucket: 'strm-mobdev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQIcpdO32YurRwLMw9_mX3W2DD0qdKSSc',
    appId: '1:724715921216:ios:77c5830a94e4413b8524a5',
    messagingSenderId: '724715921216',
    projectId: 'strm-mobdev',
    storageBucket: 'strm-mobdev.firebasestorage.app',
    iosBundleId: 'com.dominguez.strm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQIcpdO32YurRwLMw9_mX3W2DD0qdKSSc',
    appId: '1:724715921216:ios:77c5830a94e4413b8524a5',
    messagingSenderId: '724715921216',
    projectId: 'strm-mobdev',
    storageBucket: 'strm-mobdev.firebasestorage.app',
    iosBundleId: 'com.dominguez.strm',
  );
}
